import { ContentFilter } from "../../../types/feed";

export const contentFilterOptions: ContentFilter[] = [
  {
    type: "nsfw",
    label: "Explicit Sexual Images",
    visiblity: "warn",
    values: ["porn", "nsfl"],
    adult: true,
    message: "This post contains explicit sexual images",
  },
  {
    type: "nudity",
    label: "Other Nudity",
    visiblity: "warn",
    values: ["nudity"],
    adult: true,
    message: "This post contains nudity",
  },
  {
    type: "suggestive",
    label: "Sexually Suggestive",
    visiblity: "show",
    values: ["sexual"],
    adult: true,
    message: "This post contains sexually suggestive content",
  },
  {
    type: "gore",
    label: "Violent / Bloody",
    visiblity: "hide",
    values: ["gore", "self-harm", "torture", "nsfl", "corpse"],
    adult: true,
    message: "This post contains violent or bloody content",
  },
  {
    type: "hate",
    label: "Political Hate-Groups",
    visiblity: "warn",
    values: ["icon-kkk", "icon-nazi", "icon-intolerant", "behavior-intolerant"],
    adult: false,
    message: "This post has political hate content",
  },
  {
    type: "spam",
    label: "Spam",
    visiblity: "hide",
    values: ["spam"],
    adult: false,
    message: "This post has been flagged as spam",
  },
  {
    type: "impersonation",
    label: "Impersonation",
    visiblity: "warn",
    values: ["impersonation"],
    adult: false,
    message: "This post has been flagged as impersonation",
  },
];
