import { ContentFilter } from "../../../types/feed";

export const CONTENT_FILTER_OPTIONS: ContentFilter[] = [
  {
    type: "nsfw",
    label: "Explicit Sexual Images",
    visibility: "warn",
    description: "i.e pornography",
    values: ["porn", "nsfl"],
    adult: true,
    message: "Pornography",
  },
  {
    type: "nudity",
    label: "Other Nudity",
    visibility: "warn",
    description: "Including non-sexual and artistic",
    values: ["nudity"],
    adult: true,
    message: "Nudity",
  },
  {
    type: "suggestive",
    label: "Sexually Suggestive",
    visibility: "show",
    description: "Does not include nudity",
    values: ["sexual"],
    adult: true,
    message: "Sexually suggestive",
  },
  {
    type: "gore",
    label: "Violent / Bloody",
    visibility: "hide",
    description: "Including self-harm, torture",
    values: ["gore", "self-harm", "torture", "nsfl", "corpse"],
    adult: true,
    message: "Violent/bloody content",
  },
  {
    type: "hate",
    label: "Political Hate-Groups",
    visibility: "warn",
    description: "Images of groups, articles, etc.",
    values: ["icon-kkk", "icon-nazi", "icon-intolerant", "behavior-intolerant"],
    adult: false,
    message: "Political hate content",
  },
  {
    type: "spam",
    label: "Spam",
    visibility: "hide",
    description: "Excessive unwanted interactions",
    values: ["spam"],
    adult: false,
    message: "Flagged as spam",
  },
  {
    type: "impersonation",
    label: "Impersonation",
    visibility: "warn",
    description: "Accounts falsely claiming to be people or orgs",
    values: ["impersonation"],
    adult: false,
    message: "This account has been flagged as an impersonation",
  },
];
